export enum ValidateArticleError {
    INCORRECT_TITLE = 'INCORRECT_TITLE',
    INCORRECT_SUBTITLE = 'INCORRECT_SUBTITLE',
    INCORRECT_TAGS = 'INCORRECT_TAGS',
    INCORRECT_DESCRIPTION = 'INCORRECT_DESCRIPTION',
}
