export enum ValidateArticleError {
    INCORRECT_TITLE = 'INCORRECT_TITLE',
    INCORRECT_SUBTITLE = 'INCORRECT_SUBTITLE',
    INCORRECT_IMAGE = 'INCORRECT_IMAGE',
    INCORRECT_DESCRIPTION = 'INCORRECT_DESCRIPTION',
}
