name: linting, testing, building
run-name: ${{ github.actor }} run tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm ci
      - name: build production project
        run: npm run build:prod
        if: always()
      - name: linting typescript
        run: npm run lint:ts
        if: always()
      - name: linting scss
        run: npm run lint:scss
        if: always()
      - name: unit tests
        run: npm run test:unit
        if: always()
      - name: ui tests 
        uses: chromaui/action@v1
        with: 
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          onlyChanged: true
        if: always()