name: linting, testing, building
run-name: ${{ github.actor }} run tests
on:
  push:
    branches: [ origin ]
  pull_request:
    branches: [ origin ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - uses: actions/checkout@v2
      - name: String Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: $ {{ matrix.node-version }}
      - name: install modules
        run: npm ci
      - name: build production project
        run: npm run build:prod
      - name: linting typescript
        run: npm run lint:ts
      - name: linting scss
        run: npm run lint:scss
      - name: unit tests
        run: npm run test:unit